/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Scanner;
import org.example.Game;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int bigBlind;

        while (true) {
            System.out.print("What would you like the big blinds to be? ");
            String input = scanner.nextLine();

            try {
                bigBlind = Integer.parseInt(input);
                break; // exit loop if parsing succeeds
            } catch (NumberFormatException e) {
                System.out.println("Please enter a valid integer.");
            }
        }

        while (true) {
            Game.playRound(bigBlind);

            System.out.print("Would you like to play again? ");
            String input = scanner.nextLine();

            if (input.equalsIgnoreCase("no") || input.equalsIgnoreCase("n")) {
                break;
            }
            // If yes or y, loop continues for another round
        }

        scanner.close();

    }
}
